### ISSUE TITLE
A request for full code

### ISSUE THREAD

**Issue by Zandra206** [Steven-xzr/VAD_MFCC_GMM#1]
Hi！dear author，could you please share the full project code? Cuz I am doing research on this domain, and i am looking for an algorism based on MFCC GMM.it will be really nice of you. Thank you!

**Comment by Steven-xzr** [comment]
Hi!

This repo is an archive of a course project, and I'm sorry to tell you that it is no longer maintained. While the full data files are too large to upload, the code seems to be complete. Plus, I have uploaded a report in Chinese, hoping that could be helpful!
